title: File Upload Example
description: This is a test add-on to demonstrate how to upload a file
type: object
# How does this add-on accept documents
# If more than one type is specified, the user will be prompted to choose one
documents: []
properties:
  # the key is the name of the variable that will be returned to your code
  file_id:
    # the title is what will be shown as the form label
    title: File
    # a string is text
    type: string
    format: uuid
    # XXX do we need to specify this is a file?
categories: 
  - file
version: 2
